name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: make
      run: make
      
    - name: make test
      run: make test
      
    - name: make check
      run: make check
      
    - name: make run
      run: make run
      
    - name: make plot
      run: make plot
      
    - name: make clean
      run: make clean
